#-----------------------------------------------------------------------

TARGET    := rollback_cli
MFLAGS    :=
DFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N

#INCLUDE   += -I../LogFormat/
INCLUDE   += -I../../../net/include/
INCLUDE   += -I../../../base/include/
LIB       :=

LOCAL_SRC   += $(sort $(wildcard ../../../base/*.cpp))
LOCAL_SRC   += $(sort $(wildcard ../../../net/*.cpp))
include /data/code/gopath/src/git.code.oa.com/xfast/xmake/makefile.xf

#-----------------------------------------------------------------------