
#-----------------------------------------------------------------------

TARGET    := net.a
MFLAGS    :=
DFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N

#INCLUDE   += -I../LogFormat/
INCLUDE   := -I./include/
LIB       :=
#LIB       += -L../Lib/jsoncpp/src -ljsoncpp
#LIB       += -L/usr/local/mysql/lib/mysql -lmysqlclient


include /data/code/gopath/src/git.code.oa.com/xfast/xmake/makefile.xf

#-----------------------------------------------------------------------