
#-----------------------------------------------------------------------

TARGET    := net.a
MFLAGS    :=
DFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N

#INCLUDE   += -I../LogFormat/
INCLUDE   += -I./include/
INCLUDE   += -I../base/include/
LIB       :=

LOCAL_SRC   += $(sort $(wildcard ../base/*.cpp))

include /data/code/gopath/src/git.code.oa.com/xfast/xmake/makefile.xf

#-----------------------------------------------------------------------